name: AzuriomSkinApi
main: fr.Boulldogo.AzuriomSkinAPI.Main
author: Boulldogo 
version: 1.1.1
api-version: 1.13
commands: 
  skin-update: 
    permission: azuriomskinapi.skin-update
    description: Allow you to force your skin.
  azuriomskinapi-reload:
    permission: azuriomskinapi.reload
    description: Reload AzuriomSkinAPI
  forceupdate-skin:
    permission: azuriomskinapi.forceupdate
    description: Allow you to update the skin of other player.